# - Glob() adds all the files with the extension to the list
# - CPPPATH define the path where to look for source files which have include dependendcies
#		so that when these include files change, a recompilation of the source file is triggered
#		CPPPATH = ['include', '/home/project/inc']

env = Environment()
env.Program(    target='joy',
                source=[Glob('*.cpp'),
                            [   'pilibs/joystick.cpp',
                                'pilibs/serial.cpp',
                                'pilibs/utils.cpp',
                                'pilibs/log.cpp'
                            ],
                        ],
                CPPPATH = ['.','pilibs/'],
                CCFLAGS = ['-std=c++11']
            )
